### ISSUE TITLE
Setup environment - python version?

### ISSUE THREAD

**Issue by ellacharmed** [ai-practitioners/time-series-forecasting#1]
What python version are we using?

**Comment by ggjx22** [comment]
hello @ellacharmed the python version from my venv is 3.9.13. it is the default version when i set it up via `virtualenv venv`. What would be yours?

**Comment by ellacharmed** [comment]
I can specify up to 3.12 with conda, but libraries won't be available even with latest 3.11 at this time, for the libraries with solo devs.
So I'll stick with what you have.
